version: "3"

services:
  back:
    build: ./back
    command: npm run dev
    volumes:
      - ./back:/usr/src/app/back
      - /usr/src/app/back/node_modules
    environment:
      - TZ=America/Mexico_City
    ports:
      - 4000:4000
    depends_on:
      - db

  front:
    build: ./front
    volumes:
      - ./front:/usr/src/app/front
      - /usr/src/app/front/node_modules
    ports:
      - 3000:3000
    depends_on:
      - back
  
  db:
    image: mongo:4.4
    # volumes:
    #   - ./db:/data/db
    environment:
      MONGO_INITDB_DATABASE: Newsletters
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
